# Salesforce Configuration
salesforce:
  # Your Salesforce instance URL (e.g., https://na1.salesforce.com)
  # For sandbox, use: https://test.salesforce.com
  instance_url: "https://login.salesforce.com"
  api_version: "57.0"
  
  # IMPORTANT: Do not put credentials in this file!
  # Instead, set these environment variables in your shell:
  # export SF_USERNAME="your_username"
  # export SF_PASSWORD="your_password"
  # export SF_SECURITY_TOKEN="your_security_token"
  #
  # For Windows PowerShell:
  # $env:SF_USERNAME="your_username"
  # $env:SF_PASSWORD="your_password"
  # $env:SF_SECURITY_TOKEN="your_security_token"
  #
  # For Windows Command Prompt:
  # set SF_USERNAME=your_username
  # set SF_PASSWORD=your_password
  # set SF_SECURITY_TOKEN=your_security_token

# HubSpot Configuration
hubspot:
  # IMPORTANT: Do not put API key in this file!
  # Instead, set this environment variable:
  # export HUBSPOT_API_KEY="your_api_key"

# Object Mappings
objects:
  - name: "Account"
    hubspot_object: "company"
    # List of fields to extract from Salesforce
    fields:
      - name: "Name"
        hubspot_property: "name"  # Optional: if not specified, uses Salesforce field name
      - name: "Industry"
        hubspot_property: "industry"
      - name: "Type"
      - name: "BillingCity"
        hubspot_property: "city"

  - name: "Contact"
    hubspot_object: "contact"
    fields:
      - name: "FirstName"
        hubspot_property: "firstname"
      - name: "LastName"
        hubspot_property: "lastname"
      - name: "Email"
      - name: "Title"
      - name: "Phone"
        hubspot_property: "phone_number"

# Sync Settings
sync_settings:
  batch_size: 100  # Number of records to process in each batch
  max_retries: 3   # Maximum number of retry attempts for failed operations
  retry_delay: 5   # Delay between retries in seconds 